version: '3.4'

services:
  catalogdb:
    image: mongo

  microservicewithmongodb:
    image: ${DOCKER_REGISTRY-}microservicewithmongodb
    build:
      context: .
      dockerfile: MicroServiceWithMongoDb/Dockerfile

volumes:
  mongo_data: